# -*- coding: utf-8 -*-

n=input("pukidad:")
print("fk u",n)
print("the length of the string is",len(n))
dadasd = n.split()
print(dadasd)
print(dadasd[0])
print(dadasd[1])
print(dadasd[2])
print(dadasd[3])
print(dadasd[4])
print(dadasd[5])
print(dadasd[6])
print(dadasd[7])
print(dadasd[8])
print(dadasd[9])