print("-----------------------")
string_1='abc'
string_2='abc'
string_3='abcd'
print("Is string_1==string_2?")
print(string_1==string_2)
print("string_2==string_3?")
print(string_2==string_3)
print("-----------------------")
print("Is string_1==string_1.lower()?")
print(string_1==string_1.lower())
print("string_2==string_2.lower()?")
print(string_2==string_2.lower())
print("string_2==string_3.lower()?")
print(string_3==string_3.lower())
print("-----------------------")
print("Is len(string_1)==3?")
print(len(string_1)==3)
print("Is len(string_1)!=3?")
print(len(string_1)!=3)
print("Is len(string_1)>3?")
print(len(string_1)>3)
print("Is len(string_1)<3?")
print(len(string_1)<3)
print("Is len(string_1)>=3?")
print(len(string_1)>=3)
print("Is len(string_1)<=3?")
print(len(string_1)<=3)
print("-----------------------")
print(True and False)
print(True and True)
print(False and False)
print(True or False)
print(True or True)
print(False or False)
print("-----------------------")
mobileInc=['Xiaomi','Apple','Samsung','Vivo','Oppo','Huawei']
print('Apple'in mobileInc)
print('CrazyPhone'in mobileInc)
print('SmartPhone'not in mobileInc)